### ISSUE TITLE
Custom Mp4box

### ISSUE THREAD

**Issue by cleversolutions** [bloomtom/DEnc#1]
Can you make the default mp4box params configurable with those that you already have as default? To make this work nicely with dash.js I have been using -profile live and some other options to generate a bunch of m4s files.

**Comment by bloomtom** [comment]
I've committed an improvement with [0bbc670](https://github.com/bloomtom/DEnc/commit/0bbc6709ee557923cb82601b7f01430944b07e6b) and package [1.3.6](https://www.nuget.org/packages/bloomtom.DEnc/1.3.6) which hopefully addresses your use case.
You can now specify all MP4Box arguments except for input/output files and `-dash keyInterval` by passing a custom `IEncodeOptions` to `Encoder.GenerateDash`. The easiest way to do this is to create a new [H264EncodeOptions](https://github.com/bloomtom/DEnc/blob/master/DEnc/Encode/H264EncodeOptions.cs) and just set your own `AdditionalMP4BoxFlags`. Check [TestMP4BoxLiveProfile](https://github.com/bloomtom/DEnc/blob/master/DEncTests/Tests.cs) for an example.

Let me know if this addresses your use case well enough. I only did basic testing with it, as I'm personally only doing VOD transcoding using Volyar.

**Comment by cleversolutions** [comment]
Thanks Tom, that's super helpful. I have a few changes to the serialization as well to support a few more elements in the MPD. I'll send you a pull request later today or tomorrow.
