### ISSUE TITLE
How I can use the repo to merge a few MP4 files?

### ISSUE THREAD

**Issue by zydjohnHotmail** [bloomtom/DEnc#7]
Hello:
I have a few MP4 files: 0.mp4 (only video, no audio), 1.mp4 (with both audio and vidoe), 2.mp4 (both audio and video), 4.mp4 (only video, no audio).
All the mp4 files show the same size of image (1280px by 720px).
I want to merge all the above 5 mp4 files, and make a new output.mp4, with 0.mp4 at first place, 1.mp4 at the second place, 2.mp4 at the third place, 3.mp4 at the forth place and 4.mp4 at last.
Just keep the video and audio (if without audio, then simply keep it).
If we think all the mp4 files as text files, then I simply want to reach the following DOS command result:
C:\> copy 0.mp4+1.mp4+2.mp4+3.mp4+4.mp4 output.mp4
Let me know if it is possible.
I am using Visual Studio 2022 on Windows 10.
Thanks,

**Comment by bloomtom** [comment]
DEnc is a DASH encoder and manifest generator, not a general ffmpeg interface. You could probably force this to work within the library by making your own FFmpegCommand, but I wouldn't recommend it. You should instead just use ffmpeg directly using its CLI, which is quite powerful.

Try the concatenate demuxer: https://trac.ffmpeg.org/wiki/Concatenate
